version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - connection_dockers
networks:
  connection_dockers:
    external: true