version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - connection_dockers
      - connection_crud_api
networks:
  connection_dockers:
    external: true
  connection_crud_api:
    external: true