version: "3.8"
services:
  crud:
    build:
      context: .
      dockerfile: Dockerfile.crud
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - connection_dockers
      - connection_crud_api
networks:
  connection_dockers:
    external: true
  connection_crud_api:
    external: true