version: "3.8"
services:
  crud:
    container_name: crud
    build:
      context: .
      dockerfile: Dockerfile.crud
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - connection_dockers
networks:
  connection_dockers:
    external: true