version: "3.8"
services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "5000:5000"
    volumes:
      - .:/app
    networks:
      - connection_loadbalancer
networks:
  connection_loadbalancer:
    external: true