version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - default
      - connection_dockers

  pgadmin:
    image: dpage/pgadmin4
    restart: always  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8000:80"
    depends_on:
      - postgres
networks:
  default:
    driver: bridge
  connection_dockers:
    external: true