FROM python:3.9

COPY ./core /app/core
COPY ./databases/models /app/databases/models
COPY ./databases/createdatabases.py /app/databases/createdatabases.py

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "createdatabases.py", "core"]